#!/bin/zsh

if [[ $# -eq 1 ]]; then
  selected=$1
else
  # selected=$(find ~/work/builds ~/projects ~/Documents ~/work ~/personal ~/personal/yt ~/personal/ub -mindepth 1 -maxdepth 1 -type d | fzf)
  selected=$(
    # get my project's namespaces
    # I have it organized in namespaces per organization, so I have
    # my personal org (caarlos0), one for work, one for goreleaser, and so on.
      find ~/College ~/Projects ~/.config ~/Downloads ~/Documents -type d -maxdepth 1 |
      # while read -r p; do
        # get the projects in each namespace with their zoxide scores
      #z -l -r |
      # done |
      # sort -rnk1 |     # sort by zoxide score (first column)
      fzf --no-sort  # pipe to fzf without its sorting
      # awk '{print $2}' # use the path as selected (second column)
  )
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
else
  tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
